DROP DATABASE IF EXISTS T2_BBDDJuego;
CREATE DATABASE T2_BBDDJuego;

USE T2_BBDDJuego;

CREATE TABLE JUGADOR(
	ID INT NOT NULL,
	USERNAME VARCHAR(60) NOT NULL,
	PASWORD VARCHAR(60) NOT NULL,
	PRIMARY KEY(ID)
)ENGINE=InnoDB;


CREATE TABLE PARTIDA(
	ID INT NOT NULL,
	DATA VARCHAR(10) NOT NULL,
	HORAFINAL VARCHAR(5),
	DURACIO INT,
	EQUIPGUANYADOR VARCHAR(60),
	PRIMARY KEY(ID)
)ENGINE=InnODB;

CREATE TABLE PARTICIPACION(
	ID_J INT NOT NULL,
	NOMEQUIP VARCHAR(60),
	ID_P INT NOT NULL,
	PUNTS INT,
	FOREIGN KEY (ID_J) REFERENCES JUGADOR(ID),
	FOREIGN KEY (ID_P) REFERENCES PARTIDA(ID)
)ENGINE=InnODB;

INSERT INTO JUGADOR VALUES (1, 'JORDI', 'SOCTONTO');
INSERT INTO JUGADOR VALUES (2, 'JOANA', 'SOCLLESTA');
INSERT INTO JUGADOR VALUES (3, 'NURIA', 'HOLAQUETAL');
INSERT INTO JUGADOR VALUES (4, 'MIGUEL', 'BONDIA');

INSERT INTO PARTIDA VALUES (1, '13/10/2020','17:23', 20, 'EQUIP1');


INSERT INTO PARTICIPACION VALUES (1, 'EQUIP1', 1, 30);
INSERT INTO PARTICIPACION VALUES (2, 'EQUIP1', 1, 30);
INSERT INTO PARTICIPACION VALUES (3, 'EQUIP2', 1, 10);
INSERT INTO PARTICIPACION VALUES (4, 'EQUIP2', 1, 10);
